title = "r-w-x Nicholas"
baseURL = "https://nicholassynovic.github.io"
languageCode = "en-us"
theme = "ananke"
themesDir = "themes"
resourceDir = "resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Nicholas Synovic"
  favicon = ""
  site_logo = ""
  description = "Read, Write, Execute"
  background_color_class = "bg-blue"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 5 

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/nick_synovic"

